version: "2"
services:
  # このイメージのバージョンアップ = ECCUBE, PHPのバージョンアップ
  eccube:
    container_name: ${ECCUBE_CONTAINER}
    build: settings/php
    ports:
      - "${EXPOSE_ECCUBE_PORT}:80"
    links:
      - db
    environment:
      ECCUBE_DB_HOST: "db:5432"
    env_file: .env
    volumes:
      - ./html:/var/www/html
      - ./tools/shell-scripts/lib:/var/www/tools/shell-scripts
      - ./.env:/var/www/.env
      - ~/.ssh:/root/.ssh
    networks:
      main:
        aliases:
          - eccube
  db:
    container_name: ${PGSQL_CONTAINER}
    image: postgres:latest
    env_file: .env
    volumes:
      - ./settings/db:/etc/mysql/data
    networks:
      main:
        aliases:
          - db
networks:
  main:
